package org.example.employeemgmt

import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport

@OptIn(ExperimentalJsExport::class)
@JsExport
enum class EmployeeValidationErrorKeys {
    EMPLOYEE_GIVEN_NAME_BLANK,
    EMPLOYEE_SURNAME_BLANK,
    EMPLOYEE_TIN_BLANK,
    TAX_IDENTIFICATION_NUMBER_INVALID,
    PENSION_INSURANCE_NUMBER_INVALID_UNKNOWN_ERROR,
    PENSION_INSURANCE_NUMBER_FORMAT_INVALID,
    PENSION_INSURANCE_NUMBER_BIRTHDATE_INVALID,
    PENSION_INSURANCE_NUMBER_CONTROL_DIGIT_INVALID,
    PENSION_INSURANCE_NUMBER_BLANK,
    EMPLOYEE_BIRTH_DATE_IN_FUTURE,
    EMPLOYEE_BIRTH_DATE_UNDERAGE,
    EMPLOYEE_BIRTH_DATE_INVALID_UNKNOWN_ERROR
}